spring.application.name=gridflex-backend-service

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?ApplicationName=gridflex-backend-service
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.data.mongodb.uri=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB}?authSource=${MONGO_USERNAME}

springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

# Flyway settings
spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0
spring.flyway.table=flyway_schema_history_gridflex_service

file.upload-dir=/opt/java-webservices/uploads
file.base-address = https://memmcolapps.memmserve.com:8081

external.token-gen.base-url=http://169.239.189.91:19071
external.hes-endpoint.base-url=http://127.0.0.1:9061/api
external.hes-realtime.base-url=http://127.0.0.1:9061/api/realtime
external.dlms-write-ops.base-url=http://127.0.0.1:9061/api/dlms
