spring.application.name=gridflex-backend-service

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?ApplicationName=gridflex-backend-service
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.org.postgresql=DEBUG

spring.data.mongodb.uri=mongodb://${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB}

#springdoc.api-docs.enabled=true
#springdoc.swagger-ui.enabled=true

# Eureka settings
eureka.client.service-url.defaultZone=http://${EUREKA_ADDRESS}:${EUREKA_PORT}/eureka/
eureka.client.service-url.instance.prefer-ip-address=true                # Register using IP instead of hostname
eureka.client.service-url.ip-address=${spring.cloud.client.ip-address}  # Auto-detects service IP
eureka.client.service-url.instance-id=${spring.application.name}:${server.port}
eureka.client.service-url.metadata-map.management.port=${management.server.port:${server.port}}

# Flyway settings
spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0
spring.flyway.table=flyway_schema_history_gridflex_service

file.upload-dir=${UPLOAD}/uploads
file.base-address = https://${STAGING_DOMAIN}

external.token-gen.base-url=http://${T_ADDRESS}:${T_PORT}

external.hes-endpoint.base-url=http://${HES_ADDRESS}:${HES_PORT}/api
external.hes-realtime.base-url=http://${HES_ADDRESS}:${HES_PORT}/api/realtime
external.dlms-write-ops.base-url=http://${HES_ADDRESS}:${HES_PORT}/api/dlms

