spring.application.name=gridflex-backend-service

spring.datasource.url=jdbc:postgresql://172.16.10.28:8324/gridflex-DB?ApplicationName=gridflex-backend-service
spring.datasource.username=postgres
spring.datasource.password=Passw0rd0405&
spring.datasource.driver-class-name=org.postgresql.Driver

spring.data.mongodb.uri=mongodb://172.16.10.28:27017/Audit-Notification-DB

# Eureka settings
eureka.client.service-url.defaultZone=http://127.0.0.1:8761/eureka/
eureka.client.service-url.instance.prefer-ip-address=true                # Register using IP instead of hostname
eureka.client.service-url.ip-address=${spring.cloud.client.ip-address}  # Auto-detects service IP
eureka.client.service-url.instance-id=${spring.application.name}:${server.port}
eureka.client.service-url.metadata-map.management.port=${management.server.port:${server.port}}

# Flyway settings
spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0
spring.flyway.table=flyway_schema_history_gridflex_service

file.upload-dir = C:/Users/H.Soliu/Documents/Memmcol-project/uploads
file.base-address = http://localhost:443

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

external.token-gen.base-url=http://169.239.189.91:19071
external.hes-endpoint.base-url=http://127.0.0.1:9061/api
external.hes-realtime.base-url=http://127.0.0.1:9061/api/realtime
external.dlms-write-ops.base-url=http://172.16.2.73:9061/api/dlms

HEADER_KEY=custom
JWT_SECRET=%^kano&||odyssey^
ADMIN_API_VALUE=ab@#1cD3fG!mNXyZ$%Kl78&OH@beeb$
USER_API_VALUE=UvW$%12xYz!@#9LmNoP&*45QH@beeb&
SETUP_API_VALUE=Xxynhuh2b33bmuadh&8%js)!kh(h^L1
BASE_ADDRESS=grid-flex/v1/api
DOC_ADDRESS=api/v1/gridflex
PROD_DOMAIN=memmcolapps.memmserve.com
STAGING_DOMAIN=sbctest.memmserve.com

#app.base-url-path: http://localhost:9080

