spring.application.name=gridflex-backend-service


#spring.datasource.url=jdbc:postgresql://localhost:5432/gridflexDB?ApplicationName=gridflex-backend-service
#spring.datasource.username=postgres
#spring.datasource.password=root
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://172.16.10.28:8324/gridflex-DB?ApplicationName=gridflex-backend-service
spring.datasource.username=postgres
spring.datasource.password=Passw0rd0405&
spring.datasource.driver-class-name=org.postgresql.Driver

#?connectTimeout=10&sslmode=prefer
#spring.data.mongodb.uri=mongodb://localhost:27017/Audit-Notification-DB
spring.data.mongodb.uri=mongodb://172.16.10.28:27017/Audit-Notification-DB
#spring.data.mongodb.uri=mongodb://41.216.166.163:27017/Audit-Notification-DB

file.upload-dir = C:/Users/H.Soliu/Documents/Memmcol-project/uploads
