#spring.application.name=gridflex-backend-service


spring.datasource.url=jdbc:postgresql://172.16.10.28:8324/gridflex-DB?ApplicationName=gridflex-backend-service
spring.datasource.username=postgres
spring.datasource.password=Passw0rd0405&
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.data.mongodb.uri=mongodb://localhost:27017/Audit-Notification-DB
spring.data.mongodb.uri=mongodb://172.16.10.28:27017/Audit-Notification-DB
#spring.data.mongodb.uri=mongodb://41.216.166.163:27017/Audit-Notification-DB
#