server:
  port: 9080



app:
  base-path: /${BASE_ADDRESS}
#  /api/v1
#  /grid-flex/v1/api

spring:
  jackson:
    default-property-inclusion: non_null
    jackson:
      time-zone: Africa/Lagos

odyssey:
  jwt-secret: ${JWT_SECRET}

security:
  header:
    key: ${HEADER_KEY}
  admin:
    value: ${ADMIN_API_VALUE}
  user:
    value: ${USER_API_VALUE}
  setup:
    value: ${SETUP_API_VALUE}

#external:
#  token-gen:
#    base-url: http://${T_ADDRESS}:${T_PORT}
#  hes-endpoint:
#    base-url: http://${HES_ADDRESS}:${PORT}/api
#  hes-realtime:
#    base-url: http://${HES_ADDRESS}:${PORT}/api/realtime
#  dlms-write-ops:
#    base-url: http://${HES_ADDRESS}:${PORT}/api/dlms

springdoc:
  api-docs:
    path: /gridflex/api-docs

  swagger-ui:
    path: /swagger-ui.html
    config-url: /${DOC_ADDRESS}/api-docs/swagger-config
    url: /${DOC_ADDRESS}/api-docs

  packages-to-scan: org.memmcol.gridflexbackendservice.thirdPartyService

management:
  server:
    port: ${server.port}  # Use same port for actuator unless you want a separate port
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}

resilience4j:
  circuitbreaker:
    instances:
      productService:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

