spring.application.name=gridflex-backend-service


#spring.datasource.url=jdbc:postgresql://localhost:5432/gridflexDB?ApplicationName=gridflex-backend-service
#spring.datasource.username=postgres
#spring.datasource.password=root
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://172.16.10.28:8324/gridflex-DB?ApplicationName=gridflex-backend-service
spring.datasource.username=postgres
spring.datasource.password=Passw0rd0405&
spring.datasource.driver-class-name=org.postgresql.Driver

#?connectTimeout=10&sslmode=prefer
#spring.data.mongodb.uri=mongodb://localhost:27017/Audit-Notification-DB
spring.data.mongodb.uri=mongodb://172.16.10.28:27017/Audit-Notification-DB
#spring.data.mongodb.uri=mongodb://41.216.166.163:27017/Audit-Notification-DB

file.upload-dir = C:/Users/H.Soliu/Documents/Memmcol-project/uploads
file.base-address =  http://localhost:8081

external.token-gen.base-url=http://169.239.189.91:19071
external.hes-endpoint.base-url=http://127.0.0.1:9061/api
external.hes-realtime.base-url=http://127.0.0.1:9061/api/realtime
external.dlms-write-ops.base-url=http://172.16.2.73:9061/api/dlms

#app.base-url-path: http://localhost:9080

