server:
  port: 9080

app:
  base-path: /grid-flex/v1/api

spring:
  jackson:
    default-property-inclusion: non_null

#  datasource:
#    hikari:
#      maximum-pool-size: 10
#      minimum-idle: 5
#      idle-timeout: 30000
#      max-lifetime: 1800000
#      connection-timeout: 30000
#      leak-detection-threshold: 20000

#external:
#  token-gen:
#    base-url: http://169.239.189.91:19071
#  hes-endpoint:
#    base-url: http://127.0.0.1:9061/api
#  hes-realtime:
#    base-url: http://127.0.0.1:9061/api/realtime
#  dlms-write-ops:
#    base-url: http://127.0.0.1:9061/api/dlms
#    base-url: http://192.168.1.76:9061/api

external:
  token-gen:
    base-url: http://169.239.189.91:19071
  hes-realtime:
    base-url: http://192.168.1.76:9061/api/realtime
  hes-endpoint:
    base-url: http://192.168.1.76:9061/api
  dlms-write-ops:
    base-url: http://192.168.1.76:9061/api/dlms
 
#spring:
#  application:
#    name: authorization-service
#  config:
#    import: optional:configserver:http://localhost:8888
##  cloud:
##    config:
##      uri: http://localhost:8888  # Pointing to your config-service
##  sleuth:
##    sampler:
##      probability: 1.0
##  zipkin:
##    base-url: http://localhost:9411/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true                # Register using IP instead of hostname
    ip-address: ${spring.cloud.client.ip-address}  # Auto-detects service IP
    instance-id: ${spring.application.name}:${server.port}
    metadata-map:
      management.port: ${management.server.port:${server.port}}

management:
  server:
    port: ${server.port}  # Use same port for actuator unless you want a separate port
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}

resilience4j:
  circuitbreaker:
    instances:
      productService:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s


#  instance:
#    prefer-ip-address: true
#    health-check-url-path: /actuator/health
#    health-check-interval-seconds: 10

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health, info, prometheus

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    prometheus:
#      enabled: true
#  prometheus:
#    metrics:
#      export:
#        enabled: true
