spring.application.name=gridflex-backend-service

#spring.datasource.url = jdbc:sqlserver://172.16.10.29:1433;database=SmarteDB;encrypt=true;trustServerCertificate=true;
##spring.datasource.url = jdbc:sqlserver://41.216.166.163:1433;database=SmarteDB;encrypt=true;trustServerCertificate=true;
#spring.datasource.username = sa
#spring.datasource.password = Passw0rd
#spring.datasource.dbcp2.test-while-idle=true
#spring.datasource.dbcp2.validation-query=SELECT 1
#spring.main.allow-bean-definition-overriding=true

#spring.datasource.url=jdbc:postgresql://localhost:8432/gridflexdb?ApplicationName=gridflex-backend-service
#spring.datasource.username=postgres
#spring.datasource.password=Passw0rd0405&
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://172.16.10.28:8324/gridflex-DB?ApplicationName=gridflex-backend-service
spring.datasource.username=postgres
spring.datasource.password=Passw0rd0405&
spring.datasource.driver-class-name=org.postgresql.Driver

#?connectTimeout=10&sslmode=prefer
spring.data.mongodb.uri=mongodb://localhost:27017/Audit-Notification-DB
#spring.data.mongodb.uri=mongodb://172.16.10.28:27017/Audit-Notification-DB
#spring.data.mongodb.uri=mongodb://41.216.166.163:27017/Audit-Notification-DB
