#global:
#  scrape_interval: 15s
#
#scrape_configs:
#  - job_name: 'gridflex-backend-service'
#    metrics_path: '/actuator/prometheus'
#    static_configs:
#      - targets: ['localhost:9080'] # API Gateway host & port