-- Table: public.event_type

-- DROP TABLE IF EXISTS public.event_type;

CREATE TABLE IF NOT EXISTS public.event_type
(
    id bigint NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    obis_code character varying(20) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT event_type_pkey PRIMARY KEY (id)
    )

INSERT INTO public.event_type (id, name, obis_code, description) VALUES
        (1, 'Standard Event Logs', '0.0.99.98.0.255', 'General meter/system events'),
        (2, 'Power Grid Event Logs', '0.0.99.98.4.255', 'Grid-related events'),
        (3, 'Fraud Event Logs', '0.0.99.98.1.255', 'Tamper/fraud events'),
        (4, 'Control Event Logs', '0.0.99.98.2.255', 'Control/operation events'),
        (5, 'Other Event Logs', '0.0.0.0.0.255', 'Undefined Events'),
        (6, 'Uncommon Event Logs', '0.0.99.17.0.255', 'Undefined Events'),
        (7, 'Management Token Event', '0.0.99.98.11.255', 'ManageToken Event Logs'),
        (8, 'Recharge Token Event', '0.0.99.98.10.255', 'Recharge Token Event Logs'),
        (9, 'Management Token Event (household)', '0.0.99.98.5.255', 'Management Token Event household'),
        (10, 'Recharge Token Event (household)', '0.0.99.98.3.255', 'Recharge Token Event household')
        ON CONFLICT (obis_code)
        DO NOTHING;


-- Table: public.obis_mapping_data

-- DROP TABLE IF EXISTS public.obis_mapping_data;

CREATE TABLE IF NOT EXISTS public.obis_mapping_data
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    obis_code_combined character varying COLLATE pg_catalog."default",
    attribute_index character varying COLLATE pg_catalog."default",
    class_id character varying COLLATE pg_catalog."default",
    data_index character varying COLLATE pg_catalog."default",
    data_type character varying COLLATE pg_catalog."default",
    description character varying COLLATE pg_catalog."default",
    group_name character varying COLLATE pg_catalog."default",
    obis_code character varying COLLATE pg_catalog."default",
    scaler character varying COLLATE pg_catalog."default",
    unit character varying COLLATE pg_catalog."default",
    access_permission character varying COLLATE pg_catalog."default",
    ratio character varying COLLATE pg_catalog."default",
    meter_type character varying COLLATE pg_catalog."default",
    obis_type character varying COLLATE pg_catalog."default",
    operation_code character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT obis_mapping_data_pkey PRIMARY KEY (id)
    )

    INSERT INTO public.obis_mapping_data (
             obis_code_combined, attribute_index, class_id, data_index,
             data_type, description, group_name, obis_code, scaler,
             unit, access_permission, ratio, meter_type, obis_type, operation_code
         )
    VALUES
        ('4;1.0.10.6.1.255;2;0',
         '2',
         '4',
         '0',
         'BCD[3]\\Octs[12]',
         'Maximum Demand Register - Apparent energy export (-A) && occurring time of public grid',
         'Demand',
         '1.0.10.6.1.255',
         '0',
         'VA',
         'R',
         '-1',
         '1P & 3P',
         'Non-md',
         NULL
        ),
        ('4;1.0.3.6.1.255;2;0',
         '2',
         '4',
         '0',
         'BCD[3]\\Octs[12]',
         'Maximum Demand Register - Reactive energy import (+A) && occurring time of public grid',
         'Demand',
         '1.0.3.6.1.255',
         '0',
         'Var',
         'R',
         '-1',
         '3P',
         'Non-md',
         NULL
        ),
        (
            '3;1.0.15.8.1.255;2;0',
            '2',
            '3',
            NULL,
            'double-long-unsigned',
            'T1 absolute cumulative active energy register',
            'Energy',
            '1.0.15.8.1.255',
            '0',
            'KWh',
            NULL,
            NULL,
            NULL,
            'md'
        ),
        (
            '3;1.0.12.44.0.255;2;0',
            '2',
            '3',
            NULL,
            'long-unsigned',
            'Time threshold of voltage swell',
            'Threshold Parameters',
            '1.0.12.44.0.255',
            NULL,
            NULL,
            NULL,
            NULL,
            NULL,
            'md'
        ),
        (
            '1;1.0.0.4.6.255;2;0',
            '2',
            '1',
            NULL,
            'long-unsigned',
            'Denominator of PT ratio',
            'CT and PT Ratio',
            '1.0.0.4.6.255',
            NULL,
            NULL,
            NULL,
            NULL,
            NULL,
            'md'
        ),
        (
            '3;1.0.3.7.0.255;2;0',
            '2',
            '3',
            NULL,
            'double-long-unsigned',
            'Sum Li Reactive power+',
            'Instantaneous',
            '1.0.3.7.0.255',
            '0.001',
            'KW',
            NULL,
            NULL,
            NULL,
            'md'
        ),
        (
            '3;1.0.49.7.0.255;2;0',
            '2',
            '3',
            NULL,
            'double-long-unsigned',
            'L2 Apparent power+',
            'Instantaneous',
            '1.0.49.7.0.255',
            '0.001',
            'KW',
            NULL,
            NULL,
            NULL,
            'md'
        ),
        (
            '3;1.0.51.7.124.255;2;0',
            '2',
            '3',
            NULL,
            'double-long-unsigned',
            'L2 Current harmonic THD(%)',
            'Instantaneous',
            '1.0.51.7.124.255',
            '0.01',
            NULL,
            NULL,
            NULL,
            NULL,
            'md',
            NULL
        ),
        (
            '3;1.0.61.7.0.255;2;0',
            '2',
            '3',
            NULL,
            'double-long-unsigned',
            'L3 Active power+',
            'Instantaneous',
            '1.0.61.7.0.255',
            '0.001',
            'KW',
            NULL,
            NULL,
            NULL,
            'md',
            NULL
        ),
        (
            '3;1.0.3.7.0.255;2;0',
            '2',
            '3',
            '0',
            'long-unsigned',
            'Total reactive power',
            'Instantaneous',
            '1.0.3.7.0.255',
            '0',
            'Var',
            'R',
            '-1',
            '3P',
            'Non-md',
            NULL
        ),
        (
            '4;1.0.2.6.2.255;2;0',
            '2',
            '4',
            NULL,
            'double-long-unsigned',
            'T2 export active maximum demand register',
            'Maximum Demand',
            '1.0.2.6.2.255',
            '0',
            'KW',
            'R',
            '-1',
            '1P&3P',
            'md',
            NULL
        ),
        (
            '4;1.0.3.6.0.255;5;0',
            '5',
            '4',
            '0',
            'BCD[3]\\Octs[12]',
            'Maximum Demand Register - Reactive energy import (+A) && occurring time',
            'Demand',
            '1.0.3.6.0.255',
            '0',
            'Var',
            'R',
            '-1',
            '3P',
            'Non-md',
            NULL
        ),
        (
            '4;1.0.1.6.1.255;5;0',
            '5',
            '4',
            '0',
            'BCD[3]\\Octs[12]',
            'Maximum Demand Register - Active energy import (+A) && occurring time of public grid',
            'Demand',
            '1.0.1.6.1.255',
            '0',
            'W',
            'R',
            '-1',
            '1P & 3P',
            'Non-md',
            NULL
        ),
        (
            '3;1.0.3.8.4.255;2;0',
            '2',
            '3',
            NULL,
            'double-long-unsigned',
            'T4 import reactive energy register',
            'Energy',
            '1.0.3.8.4.255',
            '0',
            'KWh',
            'R',
            NULL,
            NULL,
            'md',
            NULL
        ),
        (
            '4;1.0.1.6.0.255;2;0',
            '2',
            '4',
            NULL,
            'double-long-unsigned',
            'Total import active maximum demand register',
            'Maximum Demand',
            '1.0.1.6.0.255',
            '0',
            '0.001',
            'KW',
            NULL,
            NULL,
            'md',
            NULL
        ),
        (
            NULL,
            '0',
            NULL,
            NULL,
            NULL,
            'Key expiry number',
            'Others',
            NULL,
            '0',
            NULL,
            NULL,
            NULL,
            NULL,
            'Non-md',
            NULL
        ),
        (
            '3;1.0.51.7.0.255;2;0',
            '2',
            '3',
            NULL,
            'long-unsigned',
            'L2 Current',
            'Instantaneous',
            '1.0.51.7.0.255',
            '0.01',
            'A',
            NULL,
            NULL,
            NULL,
            'md',
            NULL
        ),
        (
            '4;1.0.4.6.1.255;5;0',
            '5',
            '4',
            '0',
            'BCD[3]\\Octs[12]',
            'Maximum Demand Register - Reactive energy export (-A) && occurring time of public grid',
            'Demand',
            '1.0.4.6.1.255',
            '0',
            'Var',
            'R',
            '-1',
            '3P',
            'Non-md',
            NULL
        ),
        (
            '3;1.0.23.7.0.255;2;0',
            '2',
            '3',
            NULL,
            'double-long-unsigned',
            'L1 Reactive power+',
            'Instantaneous',
            '1.0.23.7.0.255',
            '0.001',
            'KW',
            NULL,
            NULL,
            NULL,
            'md',
            NULL
        ),
        (
            '4;1.0.2.6.3.255;2;0',
            '2',
            '4',
            NULL,
            'double-long-unsigned',
            'T3 export active maximum demand register',
            'Maximum Demand',
            '1.0.2.6.3.255',
            '0',
            'KW',
            'R',
            '-1',
            '1P&3P',
            'md',
            NULL
        ),
        (
            '3;1.0.31.7.0.255;2;0',
            '2',
            '3',
            '0',
            'long-unsigned',
            'Current in phase L1',
            'Instantaneous',
            '1.0.31.7.0.255',
            '0',
            'A',
            'R',
            '-3',
            '1P & 3P',
            'Non-md',
            NULL
        ),
        (
            NULL,
            '0',
            NULL,
            NULL,
            NULL,
            'Key type',
            'Others',
            NULL,
            '0',
            NULL,
            NULL,
            NULL,
            NULL,
            'Non-md',
            NULL
        ),
        (
            '3;1.0.71.7.124.255;2;0',
            '2',
            '3',
            NULL,
            'double-long-unsigned',
            'L3 Current harmonic THD(%)',
            'Instantaneous',
            '1.0.71.7.124.255',
            '0.01',
            NULL,
            NULL,
            NULL,
            'md',
            NULL
        ),
        (
            '4;1.0.2.6.1.255;2;0',
            '2',
            '4',
            NULL,
            'double-long-unsigned',
            'T1 export active maximum demand register',
            'Maximum Demand',
            '1.0.2.6.1.255',
            '0',
            'KW',
            'R',
            '-1',
            '1P&3P',
            'md',
            NULL
        ),
        (
            '3;1.0.2.8.3.255;2;0',
            '2',
            '3',
            NULL,
            'double-long-unsigned',
            'T3 export active energy register',
            'Energy',
            '1.0.2.8.3.255',
            '0',
            'KWh',
            'R',
            NULL,
            NULL,
            'md',
            NULL
        ),
        (
            '3;1.0.91.7.0.255;2;0',
            '2',
            '3',
            '0',
            'long-unsigned',
            'Neutral Current',
            'Instantaneous',
            '1.0.91.7.0.255',
            '0',
            'A',
            'R',
            '-3',
            '1P & 3P',
            'Non-md',
            NULL
        ),
        (
            '3;1.0.41.7.0.255;2;0',
            '2',
            '3',
            NULL,
            'double-long-unsigned',
            'L2 Active power+',
            'Instantaneous',
            '1.0.41.7.0.255',
            '0.001',
            'KW',
            NULL,
            NULL,
            NULL,
            'md',
            NULL
        ),
        (
            '3;1.0.3.8.1.255;2;0',
            '2',
            '3',
            '0',
            'double-long-unsigned',
            'Reactive energy Import (+A) of public grid',
            'Energy',
            '1.0.3.8.1.255',
            '0',
            'Varh',
            'R',
            '1',
            '3P',
            'Non-md',
            NULL
        ),
        (
            '1;1.0.0.4.3.255;2;0',
            '2',
            '1',
            NULL,
            'long-unsigned',
            'Numerator of PT ratio',
            'CT and PT Ratio',
            '1.0.0.4.3.255',
            NULL,
            NULL,
            NULL,
            NULL,
            NULL,
            'md',
            'READ_RATIO'
        ),
        (
            '3;1.0.1.7.0.255;2;0',
            '2',
            '3',
            NULL,
            'double-long-unsigned',
            'Sum Li Active power+',
            'Instantaneous',
            '1.0.1.7.0.255',
            '0.001',
            'KW',
            NULL,
            NULL,
            NULL,
            'md',
            NULL
        ),
        (
            '4;1.0.1.6.2.255;5;0',
            '5',
            '4',
            '0',
            'BCD[3]\\Octs[12]',
            'Maximum Demand Register - Active energy import (+A) && occurring time of private grid',
            'Demand',
            '1.0.1.6.2.255',
            '0',
            'W',
            'R',
            '-1',
            '1P & 3P',
            'Non-md',
            NULL
        ),
        (
            '3;1.0.1.8.1.255;2;0',
            '2',
            '3',
            NULL,
            'double-long-unsigned',
            'T1 import active energy register',
            'Energy',
            '1.0.1.8.1.255',
            '0',
            '0.001',
            'KWh',
            NULL,
            NULL,
            'md',
            NULL
        ),
        (
            '3;1.0.81.7.51.255;2;0',
            '2',
            '3',
            NULL,
            'long-unsigned',
            'Phase Angle of U(L2) - I(L2)',
            'Instantaneous',
            '1.0.81.7.51.255',
            '0.1',
            '°',
            NULL,
            NULL,
            'md',
            NULL
        ),
        (
            '1;1.0.129.129.0.255;2;0',
            '2',
            '1',
            '0',
            'OCTS',
            'Public Grid SGC code',
            'Others',
            '1.0.129.129.0.255',
            '0',
            NULL,
            'R/W',
            NULL,
            NULL,
            'Non-md',
            NULL
        ),
        (
            NULL,
            '0',
            NULL,
            NULL,
            NULL,
            'Currently active step',
            'Others',
            NULL,
            '0',
            NULL,
            NULL,
            NULL,
            NULL,
            'Non-md',
            NULL
        ),
        (
            '3;1.0.73.7.0.255;2;0',
            '2',
            '3',
            '0',
            'long-unsigned',
            'Power factor in phase L3',
            'Instantaneous',
            '1.0.73.7.0.255',
            '0',
            '/',
            'R',
            '-3',
            '3P',
            'Non-md',
            NULL
        ),
        (
            '3;1.0.8.8.0.255;2;0',
            '2',
            '3',
            NULL,
            'double-long-unsigned',
            'Total QIV reactive energy register',
            'Energy',
            '1.0.8.8.0.255',
            '0',
            'KWh',
            'R',
            NULL,
            NULL,
            'md',
            NULL
        ),
        (
            '4;1.0.2.6.0.255;2;0',
            '2',
            '4',
            '0',
            'BCD[3]\\Octs[12]',
            'Maximum Demand Register - Active energy export (-A) && occurring time',
            'Demand',
            '1.0.2.6.0.255',
            '0',
            'W',
            'R',
            '-1',
            '1P & 3P',
            'Non-md',
            NULL
        ),
        (
            '3;1.0.2.8.0.255;2;0',
            '2',
            '3',
            '0',
            'double-long-unsigned',
            'Active energy Export (-A)',
            'Energy',
            '1.0.2.8.0.255',
            '0',
            'Wh',
            'R',
            '1',
            '1P & 3P',
            'Non-md',
            NULL
        ),
        (
            '3;1.0.3.8.1.255;2;0',
            '2',
            '3',
            NULL,
            'double-long-unsigned',
            'T1 import reactive energy register',
            'Energy',
            '1.0.3.8.1.255',
            '0',
            'KWh',
            'R',
            NULL,
            NULL,
            'md',
            NULL
        ),
        (
            '3;1.0.140.129.2.255;2;0',
            '2',
            '3',
            '0',
            'INT32',
            'Public Grid Cumulative power purchase credit [kWh]',
            'Others',
            '1.0.140.129.2.255',
            '0',
            NULL,
            'R',
            NULL,
            NULL,
            'Non-md',
            NULL
        ),
        (
            '3;1.0.1.8.0.255;2;0',
            '2',
            '3',
            '0',
            'double-long-unsigned',
            'Active energy Import (+A)',
            'Energy',
            '1.0.1.8.0.255',
            '0',
            'Wh',
            'R',
            '1',
            '1P & 3P',
            'Non-md',
            NULL
        ),
        (
            '71;0.0.17.0.0.255;6;0',
            '6',
            '71',
            NULL,
            'double-long-unsigned',
            'Time threshold of over loading',
            'Threshold Parameters',
            '0.0.17.0.0.255',
            NULL,
            NULL,
            NULL,
            NULL,
            NULL,
            'md',
            NULL
        ),
        (
            '3;1.0.4.8.0.255;2;0',
            '2',
            '3',
            NULL,
            'double-long-unsigned',
            'Total export reactive energy register',
            'Energy',
            '1.0.4.8.0.255',
            '0',
            'KWh',
            'R',
            NULL,
            NULL,
            'md',
            NULL
        ),
        (
            '3;1.0.1.7.0.255;2;0',
            '2',
            '3',
            '0',
            'long-unsigned',
            'Total active power',
            'Instantaneous',
            '1.0.1.7.0.255',
            '0',
            'W',
            'R',
            '-1',
            '3P',
            'Non-md',
            NULL
        ),
        (
            '4;1.0.2.6.1.255;2;0',
            '2',
            '4',
            '0',
            'BCD[3]\\Octs[12]',
            'Maximum Demand Register - Active energy export (-A) && occurring time of public grid',
            'Demand',
            '1.0.2.6.1.255',
            '0',
            'W',
            'R',
            '-1',
            '1P & 3P',
            'Non-md',
            NULL
        ),
        (
            '4;1.0.9.6.0.255;5;0',
            '5',
            '4',
            '0',
            'BCD[3]\\Octs[12]',
            'Maximum Demand Register - Apparent energy import (+A) && occurring time',
            'Demand',
            '1.0.9.6.0.255',
            '0',
            'VA',
            'R',
            '-1',
            '1P & 3P',
            'Non-md',
            NULL
        ),
        (
            '1;1.0.129.129.0.255;2;0',
            '2',
            '1',
            '0',
            'OCTS',
            'Public Grid SGC code',
            'Others',
            '1.0.129.129.0.255',
            '0',
            NULL,
            'R/W',
            NULL,
            NULL,
            'Non-md',
            NULL
        ),
        (
            '3;1.0.4.8.0.255;2;0',
            '2',
            '3',
            '0',
            'double-long-unsigned',
            'Reactive energy Export (-A)',
            'Energy',
            '1.0.4.8.0.255',
            '0',
            'Varh',
            'R',
            '1',
            '3P',
            'Non-md',
            NULL
        ),
        (
            '3;1.0.63.7.0.255;2;0',
            '2',
            '3',
            '0',
            'long-unsigned',
            'Reactive power in phase L3',
            'Instantaneous',
            '1.0.63.7.0.255',
            '0',
            'Var',
            'R',
            '-1',
            '3P',
            'Non-md',
            NULL
        ),
        (
            NULL,
            '0',
            NULL,
            NULL,
            NULL,
            'Currently active step',
            'Others',
            NULL,
            '0',
            NULL,
            NULL,
            NULL,
            NULL,
            'Non-md',
            NULL
        ),
        (
            NULL,
            '0',
            NULL,
            NULL,
            NULL,
            'Residual credit use days',
            'Others',
            NULL,
            '0',
            NULL,
            NULL,
            NULL,
            NULL,
            'Non-md',
            NULL
        ),
        (
            '4;1.0.9.6.0.255;2;0',
            '2',
            '4',
            '0',
            'BCD[3]\\Octs[12]',
            'Maximum Demand Register - Apparent energy import (+A) && occurring time',
            'Demand',
            '1.0.9.6.0.255',
            '0',
            'VA',
            'R',
            '-1',
            '1P & 3P',
            'Non-md',
            NULL
        ),
        (
            '3;1.0.81.7.10.255;2;0',
            '2',
            '3',
            NULL,
            'long-unsigned',
            'Phase Angle of U(L2) - U(L1)',
            'Instantaneous',
            '1.0.81.7.10.255',
            '0.1',
            '°',
            NULL,
            NULL,
            NULL,
            'md',
            NULL
        ),
        (
            '3;1.0.81.7.20.255;2;0',
            '2',
            '3',
            NULL,
            'long-unsigned',
            'Phase Angle of U(L3) - U(L1)',
            'Instantaneous',
            '1.0.81.7.20.255',
            '0.1',
            '°',
            NULL,
            NULL,
            NULL,
            'md',
            NULL
        ),
        (
            '0-0:97.97.1.255;2;0',
            '2',
            '1',
            '0',
            'INT32',
            'Tariff index',
            'Others',
            '0-0:97.97.1.255',
            '0',
            NULL,
            'R',
            NULL,
            NULL,
            'Non-md',
            NULL
        ),
        (
            '4;1.0.10.6.2.255;5;0',
            '5',
            '4',
            '0',
            'BCD[3]\\Octs[12]',
            'Maximum Demand Register - Apparent energy export (-A) && occurring time of private grid',
            'Demand',
            '1.0.10.6.2.255',
            '0',
            'VA',
            'R',
            '-1',
            '1P & 3P',
            'Non-md',
            NULL
        ),
        (
            '3;1.0.1.8.1.255;2;0',
            '2',
            '3',
            '0',
            'double-long-unsigned',
            'Active energy Import (+A) of public grid',
            'Energy',
            '1.0.1.8.1.255',
            '0',
            'Wh',
            'R',
            '1',
            '1P & 3P',
            'Non-md',
            NULL
        ),
        (
            '3;1.0.7.8.0.255;2;0',
            '2',
            '3',
            NULL,
            'double-long-unsigned',
            'Total QIII reactive energy register',
            'Energy',
            '1.0.7.8.0.255',
            '0',
            'KWh',
            'R',
            NULL,
            NULL,
            'md',
            NULL
        ),
        (
            '3;1.0.32.7.0.255;2;0',
            '2',
            '3',
            '0',
            'long-unsigned',
            'Voltage in phase L1',
            'Instantaneous',
            '1.0.32.7.0.255',
            '0',
            'V',
            'R',
            '-1',
            '1P & 3P',
            'Non-md',
            NULL
        ),
        (
            '1;0.0:97.97.1.255;2;0',
            '2',
            '1',
            '0',
            'INT32',
            'Tariff index',
            'Others',
            '0-0:97.97.1.255',
            '0',
            NULL,
            'R',
            NULL,
            NULL,
            'Non-md',
            NULL
        ),
        (
            '4;1.0.2.6.2.255;2;0',
            '2',
            '4',
            '0',
            'BCD[3]\\Octs[12]',
            'Maximum Demand Register - Active energy export (-A) && occurring time of private grid',
            'Demand',
            '1.0.2.6.2.255',
            '0',
            'W',
            'R',
            '-1',
            '1P & 3P',
            'Non-md',
            NULL
        ),
        (
            '4;1.0.1.6.3.255;2;0',
            '2',
            '4',
            NULL,
            'double-long-unsigned',
            'T3 import active maximum demand register',
            'Maximum Demand',
            '1.0.1.6.3.255',
            '0',
            'KW',
            NULL,
            NULL,
            NULL,
            'md',
            NULL
        ),
        (
            '3;1.0.10.8.0.255;2;0',
            '2',
            '3',
            NULL,
            'double-long-unsigned',
            'Total export apparent energy register',
            'Energy',
            '1.0.10.8.0.255',
            '0',
            'KWh',
            'R',
            NULL,
            NULL,
            'md',
            NULL
        ),
        (
            '1;0.0.96.1.4.255;2;0',
            '2',
            '1',
            NULL,
            'octet-string',
            'E-Meter Hardware version',
            'General',
            '0.0.96.1.4.255',
            NULL,
            NULL,
            NULL,
            NULL,
            NULL,
            'md',
            NULL
        ),
        (
            '4;1.0.4.6.0.255;5;0',
            '5',
            '4',
            '0',
            'BCD[3]\\Octs[12]',
            'Maximum Demand Register - Reactive energy export (-A) && occurring time',
            'Demand',
            '1.0.4.6.0.255',
            '0',
            'Var',
            'R',
            '-1',
            '3P',
            'Non-md',
            NULL
        ),
        (
            '3;1.0.81.7.62.255;2;0',
            '2',
            '3',
            NULL,
            'long-unsigned',
            'Phase Angle of U(L3) - I(L3)',
            'Instantaneous',
            '1.0.81.7.62.255',
            '0.1',
            '°',
            NULL,
            NULL,
            NULL,
            'md',
            NULL
        ),
        (
            '3;1.0.14.7.0.255;2;0',
            '2',
            '3',
            NULL,
            'long-unsigned',
            'Frequency',
            'Instantaneous',
            '1.0.14.7.0.255',
            '0.01',
            'Hz',
            NULL,
            NULL,
            NULL,
            'md',
            NULL
        ),
        (
            '3;1.0.32.7.0.255;2;0',
            '2',
            '3',
            NULL,
            'long-unsigned',
            'L1 Voltage',
            'Instantaneous',
            '1.0.32.7.0.255',
            '0.1',
            'V',
            NULL,
            NULL,
            NULL,
            'md',
            NULL
        ),
        (
            '4;1.0.4.6.2.255;5;0',
            '5',
            '4',
            '0',
            'BCD[3]\\Octs[12]',
            'Maximum Demand Register - Reactive energy export (-A) && occurring time of private grid',
            'Demand',
            '1.0.4.6.2.255',
            '0',
            'Var',
            'R',
            '-1',
            '3P',
            'Non-md',
            NULL
        ),
        (
            '3;1.0.4.8.2.255;2;0',
            '2',
            '3',
            NULL,
            'double-long-unsigned',
            'T2 export reactive energy register',
            'Energy',
            '1.0.4.8.2.255',
            '0',
            'KWh',
            'R',
            NULL,
            NULL,
            'md',
            NULL
        ),
        (
            '3;1.0.4.8.2.255;2;0',
            '2',
            '3',
            '0',
            'double-long-unsigned',
            'Reactive energy Export (-A) of private grid',
            'Energy',
            '1.0.4.8.2.255',
            '0',
            'Varh',
            'R',
            '1',
            '3P',
            'Non-md',
            NULL
        ),
        (
            '4;1.0.9.6.2.255;2;0',
            '2',
            '4',
            '0',
            'BCD[3]\\Octs[12]',
            'Maximum Demand Register - Apparent energy import (+A) && occurring time of private grid',
            'Demand',
            '1.0.9.6.2.255',
            '0',
            'VA',
            'R',
            '-1',
            '1P & 3P',
            'Non-md',
            NULL
        ),
        (
            '3;1.0.5.8.0.255;2;0',
            '2',
            '3',
            NULL,
            'double-long-unsigned',
            'Total QI reactive energy register',
            'Energy',
            '1.0.5.8.0.255',
            '0',
            'KWh',
            'R',
            NULL,
            NULL,
            'md',
            NULL
        ),
        (
            '8;0.0.1.0.0.255.255;2;0',
            '2',
            '8',
            '0',
            'date_time',
            'Date&time',
            'Clock',
            '0.0.1.0.0.255',
            '0',
            NULL,
            'R/W',
            NULL,
            NULL,
            'Non-md',
            'READ_CLOCK'
        ),
        (
            '3;1.0.49.7.0.255;2;0',
            '2',
            '3',
            '0',
            'long-unsigned',
            'Apparent power in phase L2',
            'Instantaneous',
            '1.0.49.7.0.255',
            '0',
            'VA',
            'R',
            '-1',
            '3P',
            'Non-md',
            NULL
        ),
        (
            NULL,
            '0',
            NULL,
            NULL,
            NULL,
            'Key expiry number',
            'Others',
            NULL,
            '0',
            NULL,
            NULL,
            NULL,
            NULL,
            'Non-md',
            NULL
        ),
        (
            '71;0.0.17.0.0.255;4;0',
            '4',
            '71',
            NULL,
            'double-long-unsigned',
            'Threshold of over loading',
            'Threshold Parameters',
            '0.0.17.0.0.255',
            NULL,
            NULL,
            NULL,
            NULL,
            NULL,
            'md',
            NULL
        ),
        (
            '3;1.0.4.7.0.255;2;0',
            '2',
            '3',
            NULL,
            'double-long-unsigned',
            'Sum Li Reactive power-',
            'Instantaneous',
            '1.0.4.7.0.255',
            '0.001',
            'KW',
            NULL,
            NULL,
            NULL,
            'md',
            NULL
        ),
        (
            '3;1.0.43.7.0.255;2;0',
            '2',
            '3',
            NULL,
            'double-long-unsigned',
            'L2 Reactive power+',
            'Instantaneous',
            '1.0.43.7.0.255',
            '0.001',
            'KW',
            NULL,
            NULL,
            NULL,
            'md',
            NULL
        ),
        (
            '3;1.0.15.8.0.255;2;0',
            '2',
            '3',
            NULL,
            'double-long-unsigned',
            'Total absolute cumulative active energy register',
            'Energy',
            '1.0.15.8.0.255',
            '0',
            '0.001',
            'KWh',
            NULL,
            NULL,
            'md',
            NULL
        ),
        (
            '3;1.0.29.7.0.255;2;0',
            '2',
            '3',
            '0',
            'long-unsigned',
            'Apparent power in phase L1',
            'Instantaneous',
            '1.0.29.7.0.255',
            '0',
            'VA',
            'R',
            '-1',
            '3P',
            'Non-md',
            NULL
        ),
        (
            '3;1.0.9.7.0.255;2;0',
            '2',
            '3',
            '0',
            'long-unsigned',
            'Total apparent power',
            'Instantaneous',
            '1.0.9.7.0.255',
            '0',
            'VA',
            'R',
            '-1',
            '3P',
            'Non-md',
            NULL
        ),
        (
            '3;1.0.53.7.0.255;2;0',
            '2',
            '3',
            '0',
            'long-unsigned',
            'Power factor in phase L2',
            'Instantaneous',
            '1.0.53.7.0.255',
            '0',
            '/',
            'R',
            '-3',
            '3P',
            'Non-md',
            NULL
        ),
        (
            '1;1.0.0.4.2.255;2;0',
            '2',
            '1',
            NULL,
            'long-unsigned',
            'Numerator of CT ratio',
            'CT and PT Ratio',
            '1.0.0.4.2.255',
            NULL,
            NULL,
            NULL,
            NULL,
            NULL,
            'md',
            'READ_RATIO'
        ),
        (
            '3;1.0.52.7.0.255;2;0',
            '2',
            '3',
            NULL,
            'long-unsigned',
            'L2 Voltage',
            'Instantaneous',
            '1.0.52.7.0.255',
            '0.1',
            'V',
            NULL,
            NULL,
            NULL,
            'md',
            NULL
        ),
        (
            '4;1.0.1.6.2.255;2;0',
            '2',
            '4',
            NULL,
            'double-long-unsigned',
            'T2 import active maximum demand register',
            'Maximum Demand',
            '1.0.1.6.2.255',
            '0',
            '0.001',
            'KW',
            NULL,
            NULL,
            'md',
            NULL
        ),
        (
            '3;1.0.2.8.0.255;2;0',
            '2',
            '3',
            NULL,
            'double-long-unsigned',
            'Total export active energy register',
            'Energy',
            '1.0.2.8.0.255',
            '0',
            '0.001',
            'KWh',
            NULL,
            NULL,
            'md',
            NULL
        ),
        (
            NULL,
            '0',
            NULL,
            NULL,
            NULL,
            'Date of passive step activation',
            'Others',
            NULL,
            '0',
            NULL,
            NULL,
            NULL,
            NULL,
            'Non-md',
            NULL
        ),
        (
            NULL,
            '0',
            NULL,
            NULL,
            NULL,
            'Key type',
            'Others',
            NULL,
            '0',
            NULL,
            NULL,
            NULL,
            NULL,
            'Non-md',
            NULL
        ),
        (
            '3;1.0.14.7.0.255;2;0',
            '2',
            '3',
            '0',
            'long-unsigned',
            'Frequency',
            'Instantaneous',
            '1.0.14.7.0.255',
            '0',
            'HZ',
            'R',
            '-2',
            '1P & 3P',
            'Non-md',
            NULL
        ),
        (
            '3;1.0.72.7.0.255;2;0',
            '2',
            '3',
            NULL,
            'long-unsigned',
            'L3 Voltage',
            'Instantaneous',
            '1.0.72.7.0.255',
            '0.1',
            'V',
            NULL,
            NULL,
            NULL,
            'md',
            NULL
        ),
        (
            '4;1.0.3.6.0.255;2;0',
            '2',
            '4',
            '0',
            'BCD[3]\\Octs[12]',
            'Maximum Demand Register - Reactive energy import (+A) && occurring time',
            'Demand',
            '1.0.3.6.0.255',
            '0',
            'Var',
            'R',
            '-1',
            '3P',
            'Non-md',
            NULL
        ),
        (
            '3;1.0.41.7.0.255;2;0',
            '2',
            '3',
            '0',
            'long-unsigned',
            'Active power in phase L2',
            'Instantaneous',
            '1.0.41.7.0.255',
            '0',
            'W',
            'R',
            '-1',
            '3P',
            'Non-md',
            NULL
        ),
        (
            '3;1.0.72.7.124.255;2;0',
            '2',
            '3',
            NULL,
            'double-long-unsigned',
            'L3 Voltage harmonic THD(%)',
            'Instantaneous',
            '1.0.72.7.124.255',
            '0.01',
            NULL,
            NULL,
            NULL,
            'md',
            NULL
        ),
        (
            '1;0.0.42.0.0.255;2;0',
            '2',
            '1',
            NULL,
            'octet-string',
            'E-Meter Logical Device Name',
            'General',
            '0.0.42.0.0.255',
            NULL,
            NULL,
            NULL,
            NULL,
            'md',
            NULL
        ),
        (
            '3;1.0.15.8.4.255;2;0',
            '2',
            '3',
            NULL,
            'double-long-unsigned',
            'T4 absolute cumulative active energy register',
            'Energy',
            '1.0.15.8.4.255',
            '0',
            '0.001',
            'KWh',
            NULL,
            NULL,
            'md',
            NULL
        ),
        (
            '4;1.0.4.6.4.255;2;0',
            '2',
            '4',
            NULL,
            'double-long-unsigned',
            'T4 export reactive maximum demand register',
            'Maximum Demand',
            '1.0.4.6.4.255',
            '0',
            'KW',
            'R',
            '-1',
            '3P',
            'md',
            NULL
        ),
        (
            '4;1.0.1.6.0.255;5;0',
            '5',
            '4',
            '0',
            'BCD[3]\\Octs[12]',
            'Maximum Demand Register - Active energy import (+A) && occurring time',
            'Demand',
            '1.0.1.6.0.255',
            '0',
            'W',
            'R',
            '-1',
            '1P & 3P',
            'Non-md',
            NULL
        ),
        (
            '3;1.0.140.129.0.255;2;0',
            '2',
            '3',
            '0',
            'INT32',
            'Public Grid Credit',
            'Others',
            '1.0.140.129.0.255',
            '0',
            NULL,
            'R',
            NULL,
            NULL,
            'Non-md',
            'READ_PUBLIC_CREDIT'
        )

    ON CONFLICT (obis_code) DO NOTHING;